version: '3.7'

services:
  moodle-db:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'moodle_db:/bitnami/mariadb'
    networks:
      - moodle-network

  moodle:
    image: docker.io/bitnami/moodle:latest
    # ports:
    #   - '8080:8080'
    #   - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=moodle-db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.moodle-secure.entrypoints=websecure"
      - "traefik.http.routers.moodle-secure.rule=Host(`moodle.YOURDOMAIN`)"
    networks:
      - moodle-network
      - proxy

networks:
  moodle-network:
    external: true
  proxy:
    external: true

volumes:
  moodle_db:
    driver: local
