version: '3.7'

services:
  joomla-db:
    image: mariadb
    volumes:
      - joomla_db:/var/lib/mysql
    networks:
      - joomla-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

  joomla:
    image: joomla:latest
    environment:
      JOOMLA_DB_HOST: joomla-db
      JOOMLA_DB_USER: dbuser
      JOOMLA_DB_PASSWORD: dbpassword
      JOOMLA_DB_NAME: db
    volumes:
      - ./joomla_data:/var/www/html/
    networks:
      - proxy
      - joomla-network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.joomla-secure.entrypoints=websecure"
      - "traefik.http.routers.joomla-secure.rule=Host(`joomla.YOURDOMAIN`)"
      # - "traefik.http.routers.wordpress-secure.service=wordpress-service"
      # - "traefik.http.services.wordpress-service.loadbalancer.server.port=80"

volumes:
  joomla_db:
    driver: local

networks:
  joomla-network:
    external: true
  proxy:
    external: true
